export default function Curriculum({ active }) {
  return (
    <section className={'view' + (active ? ' active' : '')} id="view-curriculum">
      <div className="pubbar">
        <span className="dstat"><span className="ddot"></span>Draft v5 · unpublished</span>
        <span className="sp"></span>
        <button className="btnP"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2"><path d="M5 12l5 5L20 7" /></svg> Publish version</button>
        <button className="btnO"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M3 21V9l9-6 9 6v12" /></svg> Assign to schools</button>
        <span className="immut"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="5" y="11" width="14" height="9" rx="2" /><path d="M8 11V8a4 4 0 0 1 8 0v3" /></svg> Published versions are immutable</span>
      </div>
      <div className="auth">
        <div className="tree">
          <div className="ttitle"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--brand)" strokeWidth="2"><path d="M4 19V6a2 2 0 0 1 2-2h9l5 5v10" /></svg> Digital Innovation · v4</div>
          <div className="tnode"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="var(--text-subtle)" strokeWidth="2"><path d="M9 6l6 6-6 6" /></svg> Unit 1 · Getting Started with Scratch</div>
          <div className="tnode"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="var(--text-subtle)" strokeWidth="2"><path d="M9 6l6 6-6 6" /></svg> Unit 2 · Sprites &amp; Events</div>
          <div className="tnode"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="var(--text-subtle)" strokeWidth="2"><path d="M9 6l6 6-6 6" /></svg> Unit 3 · Loops &amp; Motion</div>
          <div className="tnode"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="var(--text-subtle)" strokeWidth="2"><path d="M9 6l6 6-6 6" /></svg> Unit 4 · Intro to Python</div>
          <div className="tnode"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="var(--text-subtle)" strokeWidth="2"><path d="M6 9l6 6 6-6" /></svg> Unit 5 · Robotics · Little Genius Lab™</div>
          <div className="tlesson"><span className="tnum done">1</span> What is robotics?</div>
          <div className="tlesson"><span className="tnum done">2</span> Sensors &amp; actuators</div>
          <div className="tlesson"><span className="tnum done">3</span> The Arduino board</div>
          <div className="tlesson"><span className="tnum done">4</span> Connecting Arduino</div>
          <div className="tlesson on"><span className="tnum cur">5</span> Build a Smart Reading Lamp</div>
          <div className="tlesson"><span className="tnum">6</span> Line-follower robot</div>
          <div className="addlesson">+ Add lesson</div>
        </div>
        <div className="ed">
          <div className="edlabel">Lesson title</div>
          <div className="edtitle">Build a Smart Reading Lamp</div>
          <div style={{ fontSize: '12px', color: 'var(--text-muted)', margin: '-6px 0 6px', lineHeight: 1.6 }}>Mirrors the IGNITE lesson-plan template exactly — every section below is editable and <b>optional per lesson</b>, so a short lesson uses a few blocks and a full mission uses them all. Add or remove sections freely to match any lesson pattern.</div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="9" /><path d="M12 8h.01M11 12h1v4h1" /></svg></span><h4>Overview</h4><span className="elink">Edit</span></div><div className="assessgrid"><div className="ag">Programme<b>Little Genius Robotics Lab™</b></div><div className="ag">Class · Term · Week<b>Primary 3 · T3 · Wk 5</b></div><div className="ag">Mission<b>Mission 5</b></div><div className="ag">Duration<b>90 minutes</b></div><div className="ag">Theme<b>Programming Your First Smart Invention</b></div><div className="ag">Real-world problem<b>Turn a lamp on with a button</b></div></div></div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M9 11l3 3L22 4" /><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11" /></svg></span><h4>Opening &amp; prerequisites</h4><span className="elink">Edit</span></div><div style={{ fontSize: '12.5px', color: 'var(--text-muted)', marginBottom: '8px' }}>Skills assumed from Weeks 1–4:</div><div className="matrow"><div className="matchip">What robotics is</div><div className="matchip">Physical computing</div><div className="matchip">Sensors &amp; actuators</div><div className="matchip">Arduino board</div><div className="matchip">PictoBlox interface</div><div className="matchip">Connecting Arduino</div><div className="matchip">Uploading programs</div></div></div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="9" /><circle cx="12" cy="12" r="4" /><circle cx="12" cy="12" r="1" /></svg></span><h4>Lesson framing</h4><span className="elink">Edit</span></div><div className="stepitem"><b>Real-world problem</b> — How can we build a reading lamp that turns on when we press a button?</div><div className="stepitem"><b>Big idea</b> — A robot follows instructions to solve real-life problems.</div><div className="stepitem"><b>Essential question</b> — How can we use a button, an LED and Arduino to build a smart reading lamp?</div></div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01" /></svg></span><h4>Learning outcomes</h4><span className="elink">Edit</span></div><div className="stepitem">Build a Smart Reading Lamp.</div><div className="stepitem">Connect electronic components correctly.</div><div className="stepitem">Write a simple PictoBlox program.</div><div className="stepitem">Upload the program to Arduino.</div><div className="stepitem">Test their invention &amp; explain how it works.</div></div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M9 11l3 3L22 4" /></svg></span><h4>Success criteria</h4><span className="elink">Edit</span></div><div className="chkitem"><span className="chkbox" style={{ background: 'var(--brand)', borderColor: 'var(--brand)' }}></span> I built my first invention.</div><div className="chkitem"><span className="chkbox" style={{ background: 'var(--brand)', borderColor: 'var(--brand)' }}></span> My lamp works.</div><div className="chkitem"><span className="chkbox" style={{ background: 'var(--brand)', borderColor: 'var(--brand)' }}></span> I can explain the program.</div><div className="chkitem"><span className="chkbox" style={{ background: 'var(--brand)', borderColor: 'var(--brand)' }}></span> I can identify the input and the output.</div></div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M4 7V5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2M9 20h6M12 4v16" /></svg></span><h4>Key vocabulary</h4><span className="elink">+ Add term</span></div><div className="matrow"><div className="matchip">Circuit</div><div className="matchip">LED</div><div className="matchip">Push Button</div><div className="matchip">Program</div><div className="matchip">Upload</div><div className="matchip">Sensor</div><div className="matchip">Output</div><div className="matchip">Reading Lamp</div></div></div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M4 19V6a2 2 0 0 1 2-2h9l5 5v10" /><path d="M9 4v6h6" /></svg></span><h4>NERDC curriculum link</h4><span className="elink">Edit</span></div><div className="assessgrid"><div className="ag">Theme<b>Physical Computing</b></div><div className="ag">Topic<b>Programming Physical Devices</b></div></div><div style={{ fontSize: '12.5px', color: 'var(--text-muted)', margin: '9px 0 4px' }}>Performance objectives:</div><div className="stepitem">Assemble simple electronic circuits.</div><div className="stepitem">Create simple Arduino programs.</div><div className="stepitem">Explain how programs control electronic devices.</div></div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20z" /><path d="M2 12h20" /><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10A15.3 15.3 0 0 1 12 2z" /></svg></span><h4>Real-world connection</h4><span className="elink">Edit</span></div><div style={{ fontSize: '12.5px', color: 'var(--text-muted)', marginBottom: '8px' }}>Teacher-led discussion — where and why this invention is used:</div><div style={{ fontSize: '12px', color: 'var(--text-muted)', marginBottom: '6px' }}><b>Teacher asks:</b> "Where do we use reading lamps?"</div><div className="matrow" style={{ marginBottom: '10px' }}><div className="matchip">📚 Library</div><div className="matchip">🏠 Bedroom</div><div className="matchip">🏫 Classroom</div><div className="matchip">📖 Study table</div></div><div style={{ fontSize: '12px', color: 'var(--text-muted)', marginBottom: '6px' }}><b>Teacher asks:</b> "Why are reading lamps useful?"</div><div className="matrow"><div className="matchip">Better visibility</div><div className="matchip">Protects eyesight</div><div className="matchip">Saves energy</div><div className="matchip">Helps read comfortably</div></div></div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="8" width="18" height="12" rx="2" /><path d="M7 8V6a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v2" /></svg></span><h4>Little Genius kit components</h4><span className="elink">Edit</span></div><div className="matrow"><div className="matchip">Arduino UNO</div><div className="matchip">Breadboard</div><div className="matchip">USB cable</div><div className="matchip">Push button</div><div className="matchip">LED</div><div className="matchip">220Ω resistor</div><div className="matchip">Jumper wires</div></div></div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="4" width="18" height="14" rx="2" /><path d="m3 14 4-4 4 4 3-3 4 4" /><circle cx="8" cy="9" r="1" /></svg></span><h4>Lesson media</h4><span className="elink" style={{ color: 'var(--text-subtle)', fontWeight: 600 }}>flexible · no limit</span></div>
            <div style={{ fontSize: '12px', color: 'var(--text-muted)', margin: '-2px 0 10px', lineHeight: 1.6 }}>Add <b>as many videos and images as this lesson needs</b> — drag to reorder. Some lessons carry one clip, others carry a full walkthrough set. This lesson has <b>6 videos + 2 images</b>.</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '7px' }}>
              <div className="matchip" style={{ justifyContent: 'flex-start', gap: '9px' }}><span className="mi" style={{ background: '#1e293b' }}>MP4</span> Components overview <span style={{ marginLeft: 'auto', color: 'var(--text-subtle)', fontSize: '11px' }}>2:40 · Components</span></div>
              <div className="matchip" style={{ justifyContent: 'flex-start', gap: '9px' }}><span className="mi" style={{ background: '#0f766e' }}>MP4</span> Wiring the breadboard <span style={{ marginLeft: 'auto', color: 'var(--text-subtle)', fontSize: '11px' }}>3:15 · Wiring</span></div>
              <div className="matchip" style={{ justifyContent: 'flex-start', gap: '9px' }}><span className="mi" style={{ background: '#2563EB' }}>MP4</span> Writing the PictoBlox program <span style={{ marginLeft: 'auto', color: 'var(--text-subtle)', fontSize: '11px' }}>4:05 · Programming</span></div>
              <div className="matchip" style={{ justifyContent: 'flex-start', gap: '9px', color: 'var(--text-subtle)' }}>…Upload · Testing · Challenge videos + 2 images</div>
            </div>
            <div style={{ display: 'flex', gap: '9px', marginTop: '11px' }}><button className="btnP" style={{ padding: '8px 13px', fontSize: '12.5px' }}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 5v14M5 12h14" /></svg> Add video</button><button className="btnP" style={{ padding: '8px 13px', fontSize: '12.5px', background: 'var(--surface-2)', color: 'var(--text)', border: '1px solid var(--border)' }}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 5v14M5 12h14" /></svg> Add image / GIF</button></div>
          </div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M4 4h16v16H4z" /><path d="M4 9h16M9 9v11" /></svg></span><h4>Infographic manual · LG-305</h4><span className="elink">+ Add page</span></div><div style={{ fontSize: '12px', color: 'var(--text-muted)', margin: '-2px 0 9px' }}>The step-by-step booklet learners follow — 8 pages.</div><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '7px' }}>
            <div className="matchip" style={{ justifyContent: 'flex-start', gap: '8px' }}><span className="mi" style={{ background: '#334155' }}>1</span> Real-world problem</div><div className="matchip" style={{ justifyContent: 'flex-start', gap: '8px' }}><span className="mi" style={{ background: '#334155' }}>2</span> Components needed</div>
            <div className="matchip" style={{ justifyContent: 'flex-start', gap: '8px' }}><span className="mi" style={{ background: '#334155' }}>3</span> Let's build</div><div className="matchip" style={{ justifyContent: 'flex-start', gap: '8px' }}><span className="mi" style={{ background: '#334155' }}>4</span> Let's program</div>
            <div className="matchip" style={{ justifyContent: 'flex-start', gap: '8px' }}><span className="mi" style={{ background: '#334155' }}>5</span> How it works</div><div className="matchip" style={{ justifyContent: 'flex-start', gap: '8px' }}><span className="mi" style={{ background: '#334155' }}>6</span> Where is it used?</div>
            <div className="matchip" style={{ justifyContent: 'flex-start', gap: '8px' }}><span className="mi" style={{ background: '#334155' }}>7</span> Engineering challenge</div><div className="matchip" style={{ justifyContent: 'flex-start', gap: '8px' }}><span className="mi" style={{ background: '#334155' }}>8</span> Engineering journal</div></div></div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" /></svg></span><h4>Materials</h4><span className="elink">+ Add material</span></div><div style={{ fontSize: '11px', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '.4px', color: 'var(--text-subtle)', marginBottom: '6px' }}>Teacher</div><div className="matrow" style={{ marginBottom: '10px' }}><div className="matchip">Computer</div><div className="matchip">Projector</div><div className="matchip">Working Smart Reading Lamp</div><div className="matchip"><span className="mi" style={{ background: '#ef4444' }}>PDF</span> LG-305 manual</div></div><div style={{ fontSize: '11px', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '.4px', color: 'var(--text-subtle)', marginBottom: '6px' }}>Learners</div><div className="matrow"><div className="matchip">Little Genius Kit</div><div className="matchip">Computer</div><div className="matchip">Engineering Journal</div></div></div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M3 6h18M3 12h18M3 18h12" /></svg></span><h4>Lesson flow</h4><span className="elink">Reorder</span></div><div style={{ fontSize: '12px', color: 'var(--text-muted)', margin: '-2px 0 9px' }}>Introduction → 5 teaching points → 4 class activities → infographic manual completion.</div>
            <div className="stepitem"><b>Intro · Story</b> — Professor Ignite compares an ordinary lamp with a Smart Reading Lamp.</div>
            <div className="stepitem"><b>TP1</b> Understanding the project</div><div className="stepitem"><b>TP2</b> Identify the components (input · brain · output)</div><div className="stepitem"><b>TP3</b> Build the circuit (LG-305)</div><div className="stepitem"><b>TP4</b> Program the reading lamp (PictoBlox)</div><div className="stepitem"><b>TP5</b> Test your invention (5×)</div>
            <div className="matrow" style={{ marginTop: '8px' }}><div className="matchip">A1 · Component hunt</div><div className="matchip">A2 · Circuit inspection</div><div className="matchip">A3 · Predict before upload</div><div className="matchip">A4 · Explain like an engineer</div></div>
            <div className="stepitem" style={{ marginTop: '8px' }}><b>Infographic manual</b> — Teacher completes every page of LG-305 with learners.</div></div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 3l8 4.5v9L12 21l-8-4.5v-9z" /><path d="M12 8v6M9 11h6" /></svg></span><h4>Engineering discussion</h4><span className="elink">Edit</span></div><div className="assessgrid"><div className="ag">Problem<b>Reading in the dark</b></div><div className="ag">Input<b>Push Button</b></div><div className="ag">Brain<b>Arduino</b></div><div className="ag">Output<b>LED</b></div><div className="ag">Solution<b>Smart Reading Lamp</b></div></div></div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M3 12l2-2 4 4 8-8 4 4v8H3z" /></svg></span><h4>Home engineering challenge</h4><span className="elink">Edit</span></div><div className="stepitem">Rebuild the Smart Reading Lamp from the manual and test it five times.</div><div className="stepitem">Teach a parent what the button, Arduino and LED each do.</div><div className="stepitem">Draw the invention in the Engineering Journal.</div><div className="stepitem" style={{ color: 'var(--text-subtle)' }}><b>Extension</b> — make the LED stay on a few seconds before turning off.</div></div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M4 20V10M10 20V4M16 20v-8M22 20H2" /></svg></span><h4>Assessment</h4><span className="elink">Edit</span></div><div className="assessgrid" style={{ marginBottom: '9px' }}><div className="ag">Type<b>Project + 5 questions</b></div><div className="ag">Scale<b>1–4</b></div><div className="ag">Feeds<b>LQS · Physical Computing</b></div><div className="ag">Evidence<b>Photo + 60–90s video</b></div></div><div className="stepitem"><b>1.</b> What problem does this invention solve?</div><div className="stepitem"><b>2.</b> Which component is the sensor?</div><div className="stepitem"><b>3.</b> Which component is the output?</div><div className="stepitem"><b>4.</b> Why do we need Arduino?</div><div className="stepitem"><b>5.</b> What happens when the button is pressed?</div></div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M9 11l3 3L22 4" /></svg></span><h4>Teacher observation checklist</h4><span className="elink">Edit</span></div><div className="chkitem"><span className="chkbox"></span> Built circuit correctly</div><div className="chkitem"><span className="chkbox"></span> Connected Arduino</div><div className="chkitem"><span className="chkbox"></span> Uploaded program</div><div className="chkitem"><span className="chkbox"></span> Reading Lamp worked</div><div className="chkitem"><span className="chkbox"></span> Explained the invention</div><div className="chkitem"><span className="chkbox"></span> Worked safely</div></div>

          <div className="edsec"><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="7" width="18" height="13" rx="2" /><circle cx="12" cy="13" r="3.5" /><path d="M8 7l1.5-3h5L16 7" /></svg></span><h4>Digital portfolio</h4><span className="elink">Edit</span></div><div style={{ fontSize: '12.5px', color: 'var(--text-muted)', marginBottom: '8px' }}>Parents upload from the Parent app:</div><div className="matrow"><div className="matchip"><span className="mi" style={{ background: '#0ea5e9' }}>IMG</span> Photo of the completed lamp</div><div className="matchip"><span className="mi" style={{ background: '#7c3aed' }}>MP4</span> 60–90s demo video</div></div><div style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '8px', lineHeight: 1.6 }}>Video shows the lamp on/off, names input/brain/output, and explains the program. Portfolio entry: <b>LG-305 — Smart Reading Lamp</b>.</div></div>

          <div className="edsec" style={{ marginBottom: 0 }}><div className="eh"><span className="eic"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 3a9 9 0 0 0-9 9c0 4 3 6 3 6h12s3-2 3-6a9 9 0 0 0-9-9z" /><path d="M9 21h6" /></svg></span><h4>Teacher coaching notes</h4><span className="elink">Edit</span></div><div style={{ fontSize: '12.5px', color: 'var(--text-muted)', marginBottom: '8px', lineHeight: 1.6 }}>First complete engineering experience — focus on the <b>process</b>, not just a working project. Reinforce the routine:</div><div className="matrow"><div className="matchip">1 Problem</div><div className="matchip">2 Input</div><div className="matchip">3 Brain</div><div className="matchip">4 Output</div><div className="matchip">5 Build</div><div className="matchip">6 Program</div><div className="matchip">7 Test</div><div className="matchip">8 Improve</div><div className="matchip">9 Explain</div></div><div style={{ fontSize: '12px', color: 'var(--text-subtle)', marginTop: '8px', lineHeight: 1.6 }}>If a project fails, teach debugging rather than fixing it — check wiring, review the program, test one step at a time.</div></div>
        </div>
      </div>
    </section>
  )
}
